# Generated by Django 6.1.1 on 2026-09-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('object_type', models.CharField(max_length=60, verbose_name='Тип объекта')),
                ('rooms_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номерной фонд')),
                ('message', models.TextField(blank=True, verbose_name='Задача')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Страница отправки')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('work', 'В работе'), ('closed', 'Закрыта'), ('spam', 'Спам')], default='new', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Страница открывается по /<slug>/', unique=True, verbose_name='Адрес')),
                ('icon', models.CharField(choices=[('1C', '1C'), ('KKT', 'KKT'), ('RPT', 'RPT'), ('OTA', 'OTA'), ('PMS', 'PMS'), ('EDU', 'EDU'), ('OPS', 'OPS'), ('BOOK', 'BOOK'), ('PAY', 'PAY'), ('15', '15'), ('SRCH', 'SRCH'), ('RUM', 'RUM'), ('KID', 'KID'), ('CRT', 'CRT'), ('ADM', 'ADM'), ('OFD', 'OFD'), ('RES', 'RES'), ('SRV', 'SRV'), ('WIFI', 'WIFI'), ('MON', 'MON'), ('SEC', 'SEC'), ('SCL', 'SCL'), ('LOCK', 'LOCK'), ('CARD', 'CARD'), ('CMP', 'CMP'), ('LOG', 'LOG'), ('ZON', 'ZON'), ('MIG', 'MIG')], default='OPS', max_length=16, verbose_name='Значок')),
                ('summary', models.CharField(max_length=300, verbose_name='Текст карточки')),
                ('lead', models.TextField(blank=True, verbose_name='Лид-абзац страницы')),
                ('body', models.TextField(blank=True, verbose_name='Содержимое страницы (HTML)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Title для поиска')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Description для поиска')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Блок на странице /resheniya/#<slug>', unique=True, verbose_name='Якорь')),
                ('body', models.TextField(verbose_name='Текст (HTML)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'решение',
                'verbose_name_plural': 'решения',
                'ordering': ['order', 'title'],
            },
        ),
    ]
