# Generated by Django 6.1.1 on 2026-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='group',
            field=models.CharField(choices=[('sales', 'Продажи и бронирование'), ('guest', 'Гость и сервис'), ('finance', 'Финансы и учёт'), ('infra', 'Инфраструктура'), ('chain', 'Сеть и УК'), ('launch', 'Запуск и команда')], default='launch', max_length=16, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='solution',
            name='icon',
            field=models.CharField(choices=[('1C', '1C'), ('KKT', 'KKT'), ('RPT', 'RPT'), ('OTA', 'OTA'), ('PMS', 'PMS'), ('EDU', 'EDU'), ('OPS', 'OPS'), ('BOOK', 'BOOK'), ('PAY', 'PAY'), ('15', '15'), ('SRCH', 'SRCH'), ('RUM', 'RUM'), ('KID', 'KID'), ('CRT', 'CRT'), ('ADM', 'ADM'), ('OFD', 'OFD'), ('RES', 'RES'), ('SRV', 'SRV'), ('WIFI', 'WIFI'), ('MON', 'MON'), ('SEC', 'SEC'), ('SCL', 'SCL'), ('LOCK', 'LOCK'), ('CARD', 'CARD'), ('CMP', 'CMP'), ('LOG', 'LOG'), ('ZON', 'ZON'), ('MIG', 'MIG')], default='OPS', max_length=16, verbose_name='Значок'),
        ),
        migrations.AddField(
            model_name='solution',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Лид-абзац страницы'),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description для поиска'),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title для поиска'),
        ),
        migrations.AddField(
            model_name='solution',
            name='summary',
            field=models.CharField(default='', max_length=160, verbose_name='Текст карточки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='body',
            field=models.TextField(verbose_name='Содержимое страницы (HTML)'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='slug',
            field=models.SlugField(help_text='Страница открывается по /resheniya/<slug>/', unique=True, verbose_name='Адрес'),
        ),
    ]
