# Generated by Django 6.1.1 on 2026-09-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_solution_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link_url',
            field=models.CharField(blank=True, help_text='Адрес на сайте, например /podderzhka/. Используется, только если body пуст.', max_length=200, verbose_name='Куда ведёт карточка без страницы'),
        ),
    ]
