# Generated by Django 6.1.1 on 2026-09-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Адрес')),
                ('excerpt', models.CharField(max_length=300, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Текст (HTML)')),
                ('published_at', models.DateTimeField(help_text='Дата в будущем — отложенная публикация', verbose_name='Дата публикации')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Title для поиска')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Description для поиска')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-published_at'],
            },
        ),
    ]
